version: '3'

networks:
    laravel-net:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8088:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel-net
    #Use other port then 3306 to avoid conflicts with existing mysql local installs
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel-net

    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        container_name: php
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"
        networks: 
            - laravel-net

    # docker-compose run -rm composer require author/packagename
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks: 
            - laravel-net

    # docker-compose run -rm npm install
    # docker-compose run -rm npm run dev
    npm:
        image: node:13.7
        container_name: npm
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks: 
            - laravel-net

    # docker-compose run -rm artisan migrate
    artisan:
        build:
            context: .
            dockerfile: Dockerfile-php
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        depends_on: 
            - mysql
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks: 
            - laravel-net